INSERT INTO MEMBER 
VALUES(SEQ_USERNO.NEXTVAL, 'XXX', 'XXX', 'XXX', 'X', XX, 'XXXXXXX', 'XXXXXX', 'XXXX', 'XXX', SYSDATE);

INSERT INTO MEMBER VALUES(SEQ_USERNO.NEXTVAL,'user02', 'pass02', '공유', 'M', 44,'a@gmail.com', '01011112222', '내맘속', '취미', SYSDATE);

SELECT * FROM MEMBER WHERE USERID = &

